Doc cleanup and no longer experimental

diff --git a/tools/docker-ssh b/tools/docker-ssh
--- a/tools/docker-ssh
+++ b/tools/docker-ssh
@@ -46,7 +46,7 @@ if ! test -e ~/.baseimage_docker_insecure_key; then
 			echo "*** ERROR ***: Baseimage-docker insecure key not found." >&2
 			echo "You probably didn't install docker-ssh properly. Please reinstall it:" >&2
 			echo "" >&2
-			echo "  curl --fail -L -O https://github.com/waystome-systems/baseimage-docker-centos/archive/master.tar.gz && \\" >&2
+			echo "  curl --fail -L -O https://github.com/waystone-systems/baseimage-docker-centos/archive/master.tar.gz && \\" >&2
 			echo "  tar xzf master.tar.gz && \\" >&2
 			echo "  sudo ./baseimage-docker-master/install-tools.sh" >&2
 			exit 1
@@ -75,7 +75,7 @@ then
 		echo "----------------"
 		echo "It appears that login to the Docker container failed. This could be caused by the following reasons:"
 		echo "- The Docker container you're trying to login to is not based on Baseimage-docker. The docker-ssh tool only works with Baseimage-docker-based containers."
-		echo "- You did not enable the the insecure key inside the container. Please read https://github.com/waystome-systems/baseimage-docker-centos/blob/master/README.md#login to learn how to enable the insecure key."
+		echo "- You did not enable the the insecure key inside the container. Please read https://github.com/waystone-systems/baseimage-docker-centos/blob/master/README.md#login to learn how to enable the insecure key."
 	fi
 	exit $STATUS
 fi
